### ISSUE TITLE
example code to get me going?

### ISSUE THREAD

**Issue by leoliberti** [pindakaashq/pindakaas#76]
Hi, 
can you please include some example code (using the Python interface, please) to allow me to turn some pseudoboolean constraints to SAT instances using pindakaas?
Thanks!
Yours
Leo Liberti 
<github.com/leoliberti>

**Comment by Dekker1** [comment]
Hi Leo,

Thank you for your interest. We're still working towards an initial release of the library that will include more documentation and examples. Until then, if you are running the development version, you can have a look at the test cases.
